### ISSUE TITLE
大佬有没有下载地址我体验一下，想用uni-app仿写一个

### ISSUE THREAD

**Issue by yqchilde** [shuosc/SHUhelper#35]

**Comment by kastnerorz** [comment]
看最新的 [v5](https://github.com/shuosc/SHUhelper/tree/v5) 分支，另外如果想实现跨平台不如看看 Flutter 😄

**Comment by Lotus-Blue** [comment]
> 看最新的 [v5](https://github.com/shuosc/SHUhelper/tree/v5) 分支，另外如果想实现跨平台不如看看 Flutter

你flutter用的后台单独是flask吗
